name: meshroom
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pybind11
  - numpy
  - pip  
  - pip:
      - PySide2==5.14.1
      - matplotlib>=3.1.3
      - scipy
      - pillow>=6.0.0
      - transforms3d
      - h5py
      - visdom==0.1.8.8
      - psutil>=5.6.3
      - enum34
      - markdown==2.6.11
      - requests==2.22.0
      - opencv-python
      - plyfile