name: meshroom
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - cudatoolkit=10.2
  - pytorch
  - torchvision
  - numpy
  - tqdm
  - pip  
  - pip:
      - PyQt5==5.15.0
      - PyQt5-sip==12.8.0
      - opencv-python==4.3.0.36
      - PySide2==5.14.1
      - matplotlib>=3.1.3
      - scipy
      - pillow>=6.0.0
      - numpy>=1.18.1
      - transforms3d
      - pydegensac
      - h5py
      - visdom==0.1.8.8
      - psutil>=5.6.3
      - enum34
      - markdown==2.6.11
      - requests==2.22.0
      - pybind11==2.8.1
      - opencv-python
      - plyfile
      - open3d
      - igraph
  # Debugging & development
  - jedi-language-server=0.34.11
  - jupyterlab-lsp=3.9.1
  - jupyterlab=3.2.4

